config:
    applicationVersion: 0.1-alpha
    buildNumber: 0.1.0
    developerTesting: true
    endPointLog: true
    env: DEV
    gitCommit: gitCommPH
    jenBuildId: buildIdPH
    jenBuildNum: buildNumPH
management:
    security:
        enabled: false
multipart:
    max-file-size: 100MB
    max-request-size: 100MB
pangea:
    scheduler:
        job:
            cron: 0 */1 * * * ?
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 30000
            idleTimeout: 10000
            maximum-pool-size: 20
        name: trade
        password: postgres
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/prototype
        username: trade
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
        deserialization:
            fail-on-unknown-properties: true
        mapper:
            default-view-inclusion: true
    session:
        store-type: none
